micronaut:
  application:
    name: car-rental-system

  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:5173
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            - PATCH
          allowedHeaders:
            - Content-Type
            - Authorization

logging:
  level:
    com.carrental: DEBUG
    io.micronaut: INFO